import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './ui/navbar'
import NextAuthProvider from '@/app/nextauth-provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chatter',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <Navbar></Navbar>
          <div id="main-content" className="py-4 px-3">
              {children}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
